### ISSUE TITLE
carRunner g_session not defined

### ISSUE THREAD

**Issue by ricklon** [fubarlabs/foocars#65]
The g_session is not defined.

```
_________________________________________________________
None
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/foocars/cars/carservices/carservices/carRunner.py", line 103, in imageprocessor
    with g_session.as_default():
NameError: name 'g_session' is not defined
```

**Comment by ricklon** [comment]
This is no longer required and was removed from the code as a fix.
