### ISSUE TITLE
Curator crashes when canceling a directory selection

### ISSUE THREAD

**Issue by rianders** [fubarlabs/foocars#76]
Curator crashes when canceling a directory selection.
```
Traceback (most recent call last):
  File "curator.py", line 158, in open_directory
    self.load_directory(self.loaddir)
  File "curator.py", line 206, in load_directory
    self.current_filename=self.file_list.currentItem().text()
AttributeError: 'NoneType' object has no attribute 'text'
```
![image](https://user-images.githubusercontent.com/472924/116438417-69a67780-a81c-11eb-86b5-7f773ba03016.png)

**Comment by rianders** [comment]
I think the issue is if not data files found it crashes.

**Comment by rianders** [comment]
This is now resolved.
